- hoohoo_web/.gitignore
- hoohoo_web/README.md
- hoohoo_web/package-lock.json
- hoohoo_web/package.json
- hoohoo_web/public/Images/mockData.js
- hoohoo_web/public/index.html
- hoohoo_web/src/Component/ErrorComponent/ErrorComponent.js
- hoohoo_web/src/Component/LinkToStore/LinkToStore.js
- hoohoo_web/src/Component/NotFound/NotFound.js
- hoohoo_web/src/Pages/IntroPage/Main.js
- hoohoo_web/src/Root.js
- hoohoo_web/src/Router.js
- hoohoo_web/src/index.js
> Add: Initial setting is done

- hoohoo_web/package.json
- hoohoo_web/src/Component/Nav/Nav.tsx
- hoohoo_web/src/Pages/About/AboutEarthmera.tsx
- hoohoo_web/src/Pages/About/Partners.tsx
- hoohoo_web/src/Pages/IntroPage/HomeEarthmera.tsx
- hoohoo_web/src/Pages/IntroPage/IntroSection.tsx
- hoohoo_web/src/Pages/LandingPage/EarlySignUp.tsx
- hoohoo_web/src/Pages/Partnership/AboutUs.tsx
- hoohoo_web/src/Pages/Partnership/B2B.tsx
- hoohoo_web/src/Pages/Partnership/Festival/Festival.tsx
- hoohoo_web/src/Pages/Partnership/IntroEarthMera.tsx
- hoohoo_web/src/Pages/Partnership/Vision.tsx
- hoohoo_web/src/Router.js
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
removed 4th slides.
Updated nav bar naming.
keeping Korean language setting even though we click the logo.
> Fix: minor bugs

- hoohoo_web/src/Component/Footer/Footer.tsx
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
> Fix: member name and Footer

- hoohoo_web/src/Component/ContentBox/LinedHeader.tsx
- hoohoo_web/src/Pages/Home/Download.tsx
- hoohoo_web/src/Pages/Home/HomeIntroPage.tsx
- hoohoo_web/src/Pages/Home/HomePartnership.tsx
- hoohoo_web/src/Pages/Home/HomePlatform.tsx
- hoohoo_web/src/Pages/Home/HomeTicketeer.tsx
- hoohoo_web/src/Pages/Home/Video.tsx
- hoohoo_web/src/Pages/Partnership/B2B/HowWork.tsx
- hoohoo_web/src/Pages/Partnership/B2C/EcoActionCategories.tsx
- hoohoo_web/src/Pages/Partnership/B2C/HowWork.tsx
- hoohoo_web/src/Pages/Partnership/ticketeer/HowDoesItWork.tsx
> Fix: youtube and download responsive design, minor bug fixed.

- hoohoo_web/src/Component/Footer/FootContact.tsx
- hoohoo_web/src/Pages/Home/HomeIntroPage.tsx
- hoohoo_web/src/Pages/Partnership/B2B/EMBags.tsx
- hoohoo_web/src/Pages/Partnership/B2B/PhotoVideoes.tsx
- hoohoo_web/src/Pages/Partnership/ticketeer/AskTicketeer.tsx
- hoohoo_web/src/Pages/Partnership/ticketeer/HowDoesItWork.tsx
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
> Add: Feedback Design applied.

- hoohoo_web/src/Component/ContentBox/BackgroundWithStripe.tsx
- hoohoo_web/src/Pages/Home/HomeIntroPage.tsx
Fixed landing page size.
adjusted button size.
> Fix: Landing Home Page

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Router.js
> Fix: minor design change

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Router.js
> Fix: blank page error

- hoohoo_web/src/Pages/Home/Countdown.tsx
> Fix: d-day to 7/8

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Pages/Home/HomeEarthmera.tsx
- hoohoo_web/src/Pages/Info/Redirection/RedirectPage.tsx
> Fix: D-day 8/20

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Pages/Home/HomeEarthmera.tsx
- hoohoo_web/src/Pages/Info/Redirection/RedirectPage.tsx
10 days d-day extension and fix redirect link bug.
> Fix: D-day extend 10 days

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Pages/Home/HomeEarthmera.tsx
- hoohoo_web/src/Pages/Info/Redirection/RedirectPage.tsx
for debugging redirecting link. fixed to get multiple query parameter in the link.
> Fix: redirect link

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Pages/Info/Contact/Support.tsx
- hoohoo_web/src/Pages/Info/Contact/SupportingPage.tsx
- hoohoo_web/src/Router.js
Add Supporting Page and d-day to 9/15
> Fix: d-day and add Support Page

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Pages/Info/Redirection/RedirectPage.tsx
> Fix: Store Link

- hoohoo_web/src/Pages/Info/Redirection/RedirectPage.tsx
Reverts cskangGT/hoohoo_website#67
> Revert "Fix: Store Link"

- hoohoo_web/src/Pages/Home/Countdown.tsx
- hoohoo_web/src/Pages/Home/Download.tsx
- hoohoo_web/src/Pages/Info/Redirection/RedirectPage.tsx
> Fix: double Redirect

- hoohoo_web/src/Component/Nav/Nav.tsx
- hoohoo_web/src/lang/ko.json
Hide Language setting for temp
> Fix: Hide Language for temp

- hoohoo_web/src/index.js
deleted unused font G market font
> Fix: font delete

- hoohoo_web/package-lock.json
- hoohoo_web/package.json
> Fix: build resolved

- hoohoo_web/package-lock.json
- hoohoo_web/package.json
- hoohoo_web/public/index.html
- hoohoo_web/public/sitemap.xml
- hoohoo_web/src/Pages/Home/HomeEarthmera.tsx
- hoohoo_web/src/components/opengraph/OpenGraph.tsx
- hoohoo_web/src/index.js
fixed Open Graph for Korea
fixed sitemap
> Fix: Opengraph logic

- hoohoo_web/public/index.html
- hoohoo_web/public/sitemap.xml
- hoohoo_web/src/Pages/Home/HomeEarthmera.tsx
- hoohoo_web/src/Router.js
Open Graph for Korean
and old link acceptance (https://www.earthmera.com#privacy)
> Fix: OpenGraph

- hoohoo_web/package-lock.json
- hoohoo_web/package.json
- hoohoo_web/public/index.html
- hoohoo_web/src/Pages/Home/HomeEarthmera.tsx
- hoohoo_web/src/Root.js
- hoohoo_web/src/components/opengraph/OpenGraph.tsx
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
- hoohoo_web/webpack/webpack.common.js
applied prerendering OpenGraph
> fix: Open Graph for Korea

- hoohoo_web/src/components/SEOHelmet.js
> Fix: Opengraph error

- hoohoo_web/src/Pages/Home/sections/EcoActionTestimony.tsx
> fix: padding in testimony

- hoohoo_web/src/Pages/Profile/components/ProfileWidgetGrid.tsx
- hoohoo_web/src/Pages/Profile/pages/ProfileLinkPage.tsx
- hoohoo_web/src/api/jigulink/jigulink.api.ts
- hoohoo_web/src/style.tsx
> Fix: prod api

- hoohoo_web/src/Pages/Profile/components/WidgetItem.tsx
- hoohoo_web/src/style.tsx
> Add: Profile Feature

- hoohoo_web/src/Pages/Profile/components/GoSyncView.tsx
> Fix: user link fixed

- hoohoo_web/src/Pages/Login/oauth/KakaoCallback.tsx
- hoohoo_web/src/Pages/Login/pages/Login.tsx
- hoohoo_web/src/Pages/Login/pages/Signup.tsx
- hoohoo_web/src/Pages/Profile/components/GoSyncView.tsx
- hoohoo_web/src/Pages/Profile/components/ProfileWidgetGrid.tsx
- hoohoo_web/src/Pages/Profile/components/ZiguLinkToApp.tsx
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
- hoohoo_web/src/storage/userStore.ts
> Fix: Sync page

- hoohoo_web/src/Pages/Login/pages/Login.tsx
- hoohoo_web/src/Pages/Login/pages/Signup.tsx
> hotfix: apple login closed for temp

- hoohoo_web/src/Pages/EMMedia/Testimonials/Testimonials.tsx
- hoohoo_web/src/Pages/Home/sections/HomeLandingEcoAction.tsx
- hoohoo_web/src/Pages/Partnership/ticketeer/sections/TicketeerSteps.tsx
- hoohoo_web/src/components/Nav/Nav.tsx
> Fix: Home EM landing page

- hoohoo_web/src/Pages/Login/pages/Login.tsx
- hoohoo_web/src/Pages/Login/pages/Signup.tsx
> Add: Apple login

- hoohoo_web/src/Pages/Home/sections/HomeLandingEcoAction.tsx
- hoohoo_web/src/Pages/Profile/components/CarbonWidgetContent.tsx
- hoohoo_web/src/Pages/Profile/components/FixedBottomEditView.tsx
- hoohoo_web/src/Pages/Profile/components/ProfileTopHeader.tsx
- hoohoo_web/src/Pages/Profile/components/ShareProfileModal.tsx
- hoohoo_web/src/Pages/Profile/components/WidgetItem.tsx
- hoohoo_web/src/Pages/Profile/contexts/ProfileContext.tsx
- hoohoo_web/src/Pages/Profile/pages/Profile.tsx
- hoohoo_web/src/Pages/Profile/pages/ProfileCreateWidgetPage.tsx
- hoohoo_web/src/Pages/Profile/pages/ProfileLinkPage.tsx
- hoohoo_web/src/Pages/Profile/pages/ProfileSettingPage.tsx
- hoohoo_web/src/Router.js
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
- hoohoo_web/src/util/links.ts
Added Share link modal and fixed edit mode button and add new widget button in edit mode.
> Add: Share link

- hoohoo_web/package-lock.json
- hoohoo_web/package.json
- hoohoo_web/src/Pages/Profile/pages/ProfileCreateWidgetPage.tsx
- hoohoo_web/src/Pages/Profile/pages/ProfileEditWidgetPage.tsx
- hoohoo_web/src/lang/en.json
- hoohoo_web/src/lang/ko.json
> Add: Color Picker

- hoohoo_web/src/Pages/Home/sections/HomeLandingEcoAction.tsx
- hoohoo_web/src/Pages/Profile/components/ShareProfileModal.tsx
- hoohoo_web/src/Pages/Profile/contexts/ProfileContext.tsx
- hoohoo_web/src/api/login/auth.ts
> Fix: home page landing page

- hoohoo_web/src/api/login/auth.ts
- hoohoo_web/src/lang/ko.json
> Fix: redirect

- hoohoo_web/src/lang/en.json
- zigu_web/src/Pages/Login/pages/Login.tsx
- zigu_web/src/Pages/Login/pages/PreSignup.tsx
- zigu_web/src/Pages/Login/pages/Signup.tsx
- zigu_web/src/api/login/auth.ts
- zigu_web/src/lang/ko.json
> fix: social login

- zigu_web/src/Pages/Login/pages/PlanPage.tsx
- zigu_web/src/Pages/Profile/components/FixedBottomEditView.tsx
- zigu_web/src/Pages/Profile/components/ImageCrop.tsx
- zigu_web/src/Pages/Profile/components/ProfileTopHeader.tsx
- zigu_web/src/Pages/Profile/components/ProfileWidgetGrid.tsx
- zigu_web/src/Pages/Profile/components/TemplateWidgetContent.tsx
- zigu_web/src/Pages/Profile/components/WidgetItem.tsx
- zigu_web/src/Pages/Profile/pages/ProfileCreateWidgetPage.tsx
- zigu_web/src/Pages/Profile/pages/ProfileLayoutPage.tsx
- zigu_web/src/Pages/Profile/pages/ProfileLinkPage.tsx
- zigu_web/src/Pages/Profile/types/WidgetItemType.ts
- zigu_web/src/Pages/Profile/util/EMWidgetData.ts
- zigu_web/src/api/jigulink/jigulink.api.ts
- zigu_web/src/components/Modal/ChangeTemplateModal.tsx
- zigu_web/src/components/Tooltip/CustomTooltip.tsx
- zigu_web/src/lang/en.json
- zigu_web/src/lang/i18n.js
- zigu_web/src/lang/ko.json
we updated widget to change type btw em widget and custom widget.
> Fix: tooltip added & widget update changed

- zigu_web/src/Pages/Profile/components/ProfileTopHeader.tsx
> Fix: plan and promo applied page

- zigu_web/src/style.tsx
> Fix: update widget

- zigu_web/src/Pages/Login/pages/Login.tsx
- zigu_web/src/Pages/Profile/components/ProfileTopHeader.tsx
> Fix: zigu link

- zigu_web/src/Pages/Profile/components/ProfileBackground.tsx
- zigu_web/src/Pages/Profile/components/ProfileTopHeader.tsx
- zigu_web/src/Pages/Profile/contexts/ProfileContext.tsx
- zigu_web/src/Pages/Profile/pages/ProfileLinkPage.tsx
- zigu_web/src/style.tsx
changed zigu api address from earthmera.com to zigu.my
> fix: zigu api

- zigu_web/src/style.tsx
> Fix: axios api address 

- zigu_web/src/Pages/Login/pages/PreSignup.tsx
- zigu_web/src/Pages/Login/pages/SetupProfile.tsx
> Fix: profile setting page

- hoohoo_web/src/components/Bubble.tsx
- zigu_web/src/Pages/Login/pages/Login.tsx
- zigu_web/src/Pages/Login/pages/PreSignup.tsx
- zigu_web/src/Pages/Login/pages/SelectGoal.tsx
- zigu_web/src/Pages/Login/pages/SelectPurpose.tsx
- zigu_web/src/Pages/Profile/components/TemplateWidgetContent.tsx
- zigu_web/src/Pages/Profile/components/WidgetItem.tsx
- zigu_web/src/Pages/Profile/util/EMWidgetData.ts
- zigu_web/src/api/login/auth.ts
- zigu_web/src/lang/en.json
- zigu_web/src/lang/i18n.js
- zigu_web/src/lang/ko.json
> Add: select Language 

- hoohoo_web/src/Router.js
- zigu_web/src/Pages/Profile/components/PowerByEM.tsx
- zigu_web/src/Pages/Profile/components/ProfileTopHeader.tsx
- zigu_web/src/Pages/Profile/components/WidgetItem.tsx
- zigu_web/src/Pages/Profile/pages/ProfileSettingPage.tsx
> Fix: redirect page

- hoohoo_web/src/Pages/EMMedia/EMMediaContentsPage.tsx
- hoohoo_web/src/Pages/EMMedia/PressCover/DetailContent.tsx
- hoohoo_web/src/Pages/EMMedia/PressCover/PressCoverPage.tsx
- hoohoo_web/src/Pages/EMMedia/PressCover/presscoverData.ts
- hoohoo_web/src/Pages/Home/sections/HomeEcoProducts.tsx
- hoohoo_web/src/Pages/Home/sections/HomeEcoServices.tsx
- hoohoo_web/src/Pages/Home/sections/HomeEnvImpact.tsx
- hoohoo_web/src/Pages/Home/sections/HomeLandingEcoAction.tsx
- hoohoo_web/src/Pages/Home/sections/HomePlatformGroup.tsx
- hoohoo_web/src/Pages/Home/sections/HomePlatformShare.tsx
- hoohoo_web/src/Pages/Partnership/B2C/Platform.tsx
- hoohoo_web/src/Router.js
Press coverage english version
home button navigating to page and scroll down to section
> chore: button link to section

- hoohoo_web/src/Pages/EMMedia/LinkedInPosts/postData.json
> chore: changed thumbnail image
